import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,apply,inventory} from '../lib/engine.mjs';
function setup(){const s=initialState();s.warehouses.push({id:'w1',name:'Test warehouse',capacity:10000,region:'Luzon'},{id:'w2',name:'Second test warehouse',capacity:10000,region:'Mindanao'});s.distributors.push({id:'d1',name:'Test distributor',currency:'PHP',stock:0});return s}
function run(s,table,data,action='create',id,role='Super Admin'){return apply(s,{action,table,data,id,role}).result}
function receive(s,quantity=100,expiry='2099-01-01'){const r=run(s,'movements',{type:'Stock In',product:'mango',warehouse:'w1',quantity,batch:'test batch',manufactured:'2026-01-01',expiry,reason:'Receiving'});run(s,'movements',{status:'Received',recount:quantity},'transition',r.id);return r}
function order(s,quantity=80){return run(s,'orders',{product:'mango',quantity,distributor:'d1',contact:'Test contact',delivery:'2098-01-01',channel:'Phone'})}
test('receipt is unavailable until matching supervisor recount',()=>{const s=setup();const r=run(s,'movements',{type:'Stock In',product:'mango',warehouse:'w1',quantity:100,batch:'82',manufactured:'2026-01-01',expiry:'2099-01-01',reason:'Receiving'});assert.equal(inventory(s).onHand,0);assert.throws(()=>run(s,'movements',{status:'Received',recount:99},'transition',r.id),/Recount/);assert.equal(inventory(s).onHand,0);run(s,'movements',{status:'Received',recount:100},'transition',r.id);assert.equal(inventory(s).onHand,100)});
test('allocated stock stays reserved throughout pick and pack',()=>{const s=setup();receive(s);const o=order(s);run(s,'orders',{status:'Allocated',warehouse:'w1'},'transition',o.id);for(const status of ['Picked','Packed']){run(s,'orders',{status},'transition',o.id);assert.equal(inventory(s).available,20);assert.equal(inventory(s).committed,80)}assert.throws(()=>run(s,'movements',{type:'Stock Out',product:'mango',warehouse:'w1',quantity:21,reason:'Order dispatch'}),/available/);run(s,'orders',{status:'Fulfilled'},'transition',o.id);assert.equal(inventory(s).onHand,20);assert.equal(s.distributors[0].stock,80)});
test('order above threshold requires production-owner decision',()=>{const s=setup();receive(s);const o=order(s,121);assert.equal(o.status,'Pending');assert.throws(()=>run(s,'orders',{status:'Approved',reason:'review',productionDate:'2090-01-01'},'transition',o.id,'Inventory Manager'),/production owner/);assert.throws(()=>run(s,'orders',{status:'Approved',reason:'review',productionDate:'2099-01-01'},'transition',o.id),/after required delivery/)});
test('allocation prevents double-selling and expired inventory stays unavailable',()=>{const s=setup();receive(s);s.batches.push({id:'expired',product:'mango',warehouse:'w1',quantity:100,expiry:'2020-01-01'});const a=order(s,80);run(s,'orders',{status:'Allocated',warehouse:'w1'},'transition',a.id);assert.equal(inventory(s).available,20);const b=order(s,20);assert.throws(()=>run(s,'orders',{status:'Allocated',warehouse:'w2'},'transition',b.id),/Insufficient/)});
test('FEFO transfer preserves batch traceability and total stock',()=>{const s=setup();receive(s,50,'2099-01-01');receive(s,50,'2090-01-01');run(s,'movements',{type:'Stock Transfer',product:'mango',warehouse:'w1',destination:'w2',quantity:30,reason:'Warehouse transfer'});assert.equal(inventory(s).onHand,100);assert.equal(s.batches.find(b=>b.warehouse==='w2').expiry,'2090-01-01');assert.equal(inventory(s,null,'w2').onHand,30)});
test('stale count cannot overwrite changed stock',()=>{const s=setup();receive(s);const c=run(s,'counts',{product:'mango',warehouse:'w1',actual:99,reason:'Count correction'});receive(s,10);assert.throws(()=>run(s,'counts',{status:'Approved'},'transition',c.id),/Stock changed/)});
test('return liability does not make returned stock saleable',()=>{const s=setup();const r=run(s,'returns',{product:'mango',distributor:'d1',quantity:10,reason:'Damage',damageStage:'After distributor receipt'});assert.equal(r.liability,'Distributor');run(s,'returns',{status:'Approved',reason:'Policy reviewed'},'transition',r.id);assert.equal(inventory(s).available,0)});
test('import rejects unknown products and never creates orders',()=>{const s=setup();assert.throws(()=>run(s,'imports',{distributor:'d1',rows:[{product:'unknown',stock:1,sold:1}]}),/Unknown product/);run(s,'imports',{distributor:'d1',rows:[{product:'Mango',stock:100,sold:20}]});assert.equal(s.orders.length,0);assert.equal(s.distributors[0].sold,20)});
test('payment cannot exceed invoice total',()=>{const s=setup();receive(s);order(s);const i=s.invoices[0];assert.throws(()=>run(s,'invoices',{amount:100,paid:101,due:'2099-01-01'},'update',i.id),/between zero/);run(s,'invoices',{amount:100,paid:25,due:'2099-01-01'},'update',i.id);assert.equal(i.status,'Partial')});
test('warehouse capacity is enforced and duplicate receipts blocked',()=>{const s=setup();s.warehouses[0].capacity=100;const r=receive(s);assert.throws(()=>receive(s,1),/capacity/);assert.throws(()=>run(s,'movements',{status:'Received',recount:100},'transition',r.id),/already/)});
