import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initialState} from '../lib/engine.mjs';
import {answerInventory} from '../lib/inventory-assistant.mjs';
const date=n=>new Date(Date.parse(new Date().toISOString().slice(0,10))+n*86400000).toISOString().slice(0,10);
function fixture(){const s=initialState();s.products.forEach(p=>p.reorder=10);s.warehouses=[{id:'w',name:'North',region:'Luzon',territory:'Region I',capacity:1000}];s.distributors=[{id:'d',name:'Bonko partner',region:'Luzon',territory:'Region I',positions:[{product:'mango',stock:25,sold:10}]}];s.batches=[{id:'a',batch:'Within month',product:'mango',warehouse:'w',quantity:100,expiry:date(15)},{id:'b',batch:'Within two months',product:'mango',warehouse:'w',quantity:50,expiry:date(45)},{id:'c',batch:'Expired',product:'mango',warehouse:'w',quantity:12,expiry:date(-1)},{id:'d',batch:'No stock',product:'mango',warehouse:'w',quantity:0,expiry:date(4)}];return s;}
test('expiry excludes expired and empty batches and respects the selected horizon',()=>{const s=fixture();assert.deepEqual(answerInventory(s,'expiry in 1 month').rows.map(r=>r.name),['Within month']);assert.deepEqual(answerInventory(s,'expiry in 2 months').rows.map(r=>r.name),['Within month','Within two months']);});
test('stock distinguishes holdings from available stock',()=>{const a=answerInventory(fixture(),'inventory overview');assert.equal(a.metrics[0].value,162);assert.equal(a.metrics[1].value,150);assert.equal(a.metrics[2].value,25);assert.equal(a.rows[0].value,187);});
test('region and distributor scope do not leak other stock',()=>{assert.equal(answerInventory(fixture(),'inventory',{area:'Mindanao'}).metrics[0].value,0);const a=answerInventory(fixture(),'inventory',{distributor:'d'});assert.equal(a.metrics[0].value,0);assert.equal(a.metrics[2].value,25);assert.equal(a.scope,'Bonko partner');});
test('follow-up retains expiry intent and resolves two-month range',()=>{const a=answerInventory(fixture(),'What about 2 months?',{previousIntent:'expiry'});assert.equal(a.intent,'expiry');assert.equal(a.rows.length,2);});
test('unknown requests receive guidance and never change inventory',()=>{const s=fixture(),original=JSON.stringify(s);assert.equal(answerInventory(s,'Write a poem about space').intent,'help');answerInventory(s,'Delete all stock');assert.equal(JSON.stringify(s),original);});
