export const modules=[
 ['dashboard','Overview','Your daily view of inventory, risk, and the next best action.','LayoutDashboard','WORKSPACE'],
 ['inventory','Inventory','Track Bonko stock by SKU, batch, and warehouse.','Package',''],
 ['warehouses','Warehouses','Manage locations, capacity, and warehouse access.','Warehouse',''],
 ['distributors','Distributor network','Reconcile distributor-held stock and reported sell-through.','Network',''],
 ['orders','Orders','Enter orders manually, review thresholds, and reserve stock.','ShoppingBag',''],
 ['purchasing','Purchasing','Manage suppliers and purchase orders through approved receipt.','ShoppingCart','OPERATIONS'],
 ['fulfillment','Fulfillment','Allocate, pick, pack, and dispatch orders using FEFO.','Truck',''],
 ['counting','Stock counts','Compare physical quantities with expected stock and approve variances.','ClipboardCheck',''],
 ['barcodes','Barcodes','Generate and link barcodes to batches, then use them in stock workflows.','ScanLine',''],
 ['quality','Shelf life & quality','Prioritize expiring batches and understand inventory wastage.','CalendarClock',''],
 ['returns','Returns','Review damaged and expired returns and assign policy liability.','Undo2',''],
 ['analytics','Sales performance','Compare reported sales-to-trade and dispatches to distributors.','ChartNoAxesCombined','INTELLIGENCE'],
 ['forecasting','AI insights','Review explainable recommendations and log manager overrides.','Sparkles',''],
 ['receivables','Accounts receivable','Track order-linked invoices, payments, and outstanding balances.','Wallet',''],
 ['reports','Reports & exports','Build management reports and export your current workspace data.','FileChartColumn',''],
 ['integrations','Data & integrations','Map CSV or Excel files and reconcile stock without creating orders.','Cable','ADMINISTRATION'],
 ['users','Users & roles','Configure role permissions and warehouse access for your team.','Users',''],
 ['audit','Audit & activity','Trace stock changes, decisions, and imports in one searchable history.','History','']
];
export type Field={key:string,label:string,type?:string,options?:string[],source?:string,required?:boolean,help?:string};
const f=(key:string,label:string,type='text',extra:any={}):Field=>({key,label,type,required:true,...extra});
const product=f('product','Product','select',{source:'products'}), warehouse=f('warehouse','Warehouse','select',{source:'warehouses'}), qty=f('quantity','Quantity · bottles','number'), reason=f('reason','Reason','textarea');
export const schemas:Record<string,Field[]>={
 products:[f('name','Product name'),f('sku','SKU'),f('flavor','Flavor'),f('size','Size'),f('pack','Pack variant'),f('brand','Brand'),f('category','Category'),f('subcategory','Sub-category','text',{required:false}),f('image','Product image URL','url',{required:false}),f('status','Status','select',{options:['Active','Inactive']}),f('unit','Base unit'),f('carton','Bottles per carton','number'),f('pallet','Cartons per pallet','number'),f('reorder','Reorder level · bottles','number')],
 warehouses:[f('name','Warehouse name'),f('location','Location'),f('region','Region','select',{options:['Luzon','Mindanao','Modern Trade']}),f('territory','Region / territory','select',{options:['Region I','Region IV A & IV B','Region III','Region V','Region IX','Region X','Region XI','Region XII','Modern Trade']}),f('capacity','Capacity · bottles','number'),f('access','Warehouse access','select',{options:['Warehouse Manager','Warehouse Staff','Inventory Manager']})],
 distributors:[f('name','Distributor name'),f('region','Region','select',{options:['Luzon','Mindanao','Modern Trade']}),f('territory','Region / territory','select',{options:['Region I','Region IV A & IV B','Region III','Region V','Region IX','Region X','Region XI','Region XII','Modern Trade']}),f('contact','Contact name'),f('phone','Phone','tel',{required:false}),f('email','Email','email',{required:false}),f('method','Data intake','select',{options:['Manual','File upload','API']}),f('currency','Currency code'),f('exchangeTiming','Exchange-rate timing','select',{options:['Order receipt','Invoice raised']}),f('paymentTerms','Payment terms','text',{required:false})],
 orders:[f('distributor','Distributor','select',{source:'distributors'}),product,qty,f('channel','Order channel','select',{options:['Phone','Email','Distributor system','Other']}),f('contact','Contact who placed the order'),f('delivery','Required delivery','date'),f('notes','Order notes','textarea',{required:false})],
 movements:[f('type','Stock action','select',{options:['Stock In','Stock Out','Stock Transfer','Adjustment']}),product,warehouse,qty,f('reason','Reason code','select',{options:['Receiving','Order dispatch','Warehouse transfer','Count correction','Damage','Breakage']}),f('batch','Batch number','text',{required:false}),f('manufactured','Manufacturing date','date',{required:false}),f('expiry','Expiry date','date',{required:false}),f('destination','Destination warehouse','select',{source:'warehouses',required:false}),f('barcode','Scanned barcode','text',{required:false}),f('purchase','Purchase order','select',{source:'purchases',required:false})],
 suppliers:[f('name','Supplier name'),f('contact','Contact'),f('leadTime','Lead time · days','number'),f('onTime','On-time delivery rate · %','number')],
 purchases:[f('supplier','Supplier','select',{source:'suppliers'}),product,qty,f('delivery','Expected receipt','date'),f('notes','Purchase notes','textarea',{required:false})],
 returns:[f('distributor','Distributor','select',{source:'distributors'}),product,qty,f('batch','Batch number'),f('reason','Return reason','select',{options:['Damage','Expired']}),f('damageStage','Damage occurred','select',{options:['Before dispatch','After distributor receipt']}),f('notes','Policy notes','textarea',{required:false})],
 counts:[product,warehouse,f('scheduled','Count date','date'),f('mode','Count type','select',{options:['Ad hoc','Scheduled']}),f('actual','Actual quantity · bottles','number'),reason],
 barcodes:[product,warehouse,f('batch','Batch','select',{source:'batches'}),f('code','Barcode value','text',{help:'Code 128 · unique to the batch'})],
 connections:[f('name','Connection name'),f('distributor','Distributor','select',{source:'distributors'}),f('endpoint','Stock synchronization endpoint','url'),f('frequency','Sync frequency','select',{options:['Real-time API','Weekly batch']}),f('notes','Integration requirements','textarea',{required:false})],
 reports:[f('name','Report name'),f('dataset','Dataset','select',{options:['Inventory','Orders','Distributor stock','Sales to trade','Accounts receivable','Audit history']}),f('frequency','Frequency','select',{options:['Daily','Weekly','Monthly']}),f('format','Export format','select',{options:['Excel','PDF']}),f('nextRun','Next run','date')],
 users:[f('name','Full name'),f('email','Email','email'),f('role','Role','select',{options:['Super Admin','Inventory Manager','Warehouse Manager','Warehouse Staff','Distributor','Production Owner','Finance/Admin']}),f('warehouse','Warehouse access','select',{source:'warehouses',required:false})],
 events:[f('name','Factor / event'),product,f('region','Region','select',{options:['Luzon','Mindanao','Modern Trade']}),f('type','Factor type','select',{options:['Weather / climate','Local festival','Confirmed production','Large order','Promotion / sampling','Expiry-driven dispatch','New untracked factor']}),f('date','Event date','date'),f('quantity','Confirmed production quantity','number',{required:false}),f('notes','Evidence and expected impact','textarea')],
 overrides:[f('recommendation','Recommendation'),f('decision','Manager decision','select',{options:['Increase','Hold','Reduce','Prioritize dispatch','Review']}),reason],
 invoices:[f('amount','Confirmed invoice total','number'),f('paid','Total payment received','number'),f('due','Payment due date','date'),f('exchangeRate','Applicable point-in-time exchange rate','number'),reason],
 rules:[f('name','Rule name'),f('multiplier','Maximum order / available stock','number'),reason],
 settings:[f('expiryDays','Expiry warning lead time · days','number'),f('receiptApproval','Require supervisor recount','select',{options:['Yes','No']}),f('recipients','Alert recipient roles','text',{help:'Separate roles with commas'})]
};
export const examples=[{title:'Prioritize Batch #82 for dispatch',why:'The document illustrates a batch expiring in four days. FEFO prioritizes the earliest expiry.',tag:'Shelf life',route:'quality'},{title:'Review Mango production in Region A',why:'The document describes excess Mango inventory. Reduce the next cycle when stock exceeds demand.',tag:'Production',route:'forecasting'},{title:'Review Blackcurrant sell-through',why:'The document illustrates a 20% month-over-month decline in Region A.',tag:'Demand',route:'analytics'},{title:'Hold shipments to Distributor X',why:'The document illustrates stock at roughly 3× average sell-through.',tag:'Allocation',route:'distributors'}];
