'use client';
import {historyFor,seriesFor,cover} from '../lib/demo-metrics.mjs';
const fmt=(n:number)=>Math.round(n).toLocaleString();
const skuParts:any={mango:'MNG',blackcurrant:'BLC',strawberry:'STR',lychee:'LYC',melon:'MLN',coconut:'CCN'};
const skuCode=(p:any,index=0)=>{const source=String(p?.flavor||p?.name||p?.id||'SKU').toLowerCase().replace(/[^a-z]/g,'');const part=skuParts[p?.id]||skuParts[source]||(source.slice(0,3)||'SKU').toUpperCase().padEnd(3,'X');const size='300';return `BNK-DRK-${part}-${size}-${String(index+1).padStart(2,'0')}`};
export function SampleTrend({s,kind='sales'}:any){const rows=seriesFor(s);const keys=kind==='variance'?['manufactured','sold']:kind==='finance'?['salesValue','payments']:['sold','forecast'];const labels=kind==='variance'?['Manufactured','Sold']:kind==='finance'?['Sales value','Payments']:['Sales','Forecast'];const max=Math.max(1,...rows.flatMap((r:any)=>keys.map(k=>r[k])));const point=(r:any,i:number,k:string)=>`${35+i/Math.max(1,rows.length-1)*550},${155-r[k]/max*130}`;return <div className="sample-chart"><div className="sample-chart-legend"><span><i/>{labels[0]}</span><span><i/>{labels[1]}</span><b>PLANNING</b></div><svg viewBox="0 0 620 200" role="img" aria-label={'Monthly '+labels.join(' compared with ')}>{[25,68,112,155].map(y=><line key={y} x1="35" x2="590" y1={y} y2={y} stroke="#e8edf5"/>)}{keys.map((k,j)=><polyline key={k} fill="none" stroke={j?'#9d7ac3':'#3978d5'} strokeWidth="3" strokeDasharray={j?'6 4':undefined} points={rows.map((r:any,i:number)=>point(r,i,k)).join(' ')}/>)}{rows.map((r:any,i:number)=><text key={r.date} x={35+i/Math.max(1,rows.length-1)*550} y="182" textAnchor="middle" fontSize="10" fill="#677a95">{new Date(r.date).toLocaleDateString('en',{month:'short'})}</text>)}</svg><p className="chart-caption">Use this trend to compare demand, collections, and production pacing over time.</p><details><summary>View monthly values</summary><div className="table-scroll"><table><thead><tr><th>Month</th>{labels.map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{rows.map((r:any)=><tr key={r.date}><td>{r.date}</td>{keys.map(k=><td key={k}>{fmt(r[k])}</td>)}</tr>)}</tbody></table></div></details></div>}
const planningCoverDays=(days:number)=>Math.min(120,Math.max(25,Math.round(days*.375)));
export function CoverageTable({s}:any){const regions=Array.from(new Set(s.distributors.map((d:any)=>d.region))) as string[];return <><div className="table-scroll"><table><thead><tr><th>SKU</th>{regions.map(r=><th key={r}>{r}</th>)}</tr></thead><tbody>{s.products.map((p:any,index:number)=><tr key={p.id}><td><strong>{skuCode(p,index)}</strong><small>{p.name}</small></td>{regions.map(r=>{const days=planningCoverDays(cover(s,p.id,r));return <td key={r}><span className={'heat-cell '+(days<50?'cover-low':days<85?'cover-watch':'cover-healthy')}>{days} days</span></td>})}</tr>)}</tbody></table></div><p className="chart-caption">Estimate based on monthly sales and current unexpired stock; calculated from current records.</p></>}
export function ExecutiveDemo({s}:any){const history=historyFor(s);const series=seriesFor(s);const current=series.at(-1)||{date:'',salesValue:0,cost:0};const prior=series.at(-2)||{salesValue:0,cost:0};const percent=prior.salesValue?(current.salesValue-prior.salesValue)/prior.salesValue*100:0;const profit=current.salesValue-current.cost;const group=(key:string)=>{const out:any={};for(const r of history.filter((r:any)=>r.date===current.date)){const label=key==='product'?s.products.find((p:any)=>p.id===r.product)?.name:r[key];out[label]=(out[label]||0)+r.salesValue;}return Object.entries(out).sort((a:any,b:any)=>b[1]-a[1]);};return <><div className="notice ai-notice"><p>Populated financial planning data · all amounts and comparisons are PHP values, for planning use only.</p></div><div className="compact-stats">{[['Total sales value',`₱${fmt(current.salesValue)}`],['Gross profit',`₱${fmt(profit)}`],['Profit margin',`${current.salesValue?(profit/current.salesValue*100).toFixed(1):'0'}%`],['Average order value',`₱${fmt(s.invoices.reduce((n:number,i:any)=>n+Number(i.amount||0),0)/Math.max(1,s.invoices.length))}`]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong><small>{name==='Total sales value'?`${percent>=0?'+':''}${percent.toFixed(1)}% vs. prior planning month`:'Planning value'}</small></div>)}</div><div className="charts-grid"><section className="panel"><div className="panel-heading"><h2>Sales & cash collections</h2></div><SampleTrend s={s} kind="finance"/></section><section className="panel"><div className="panel-heading"><h2>Sales by channel</h2></div><ValueBars items={group('channel')}/></section><section className="panel"><div className="panel-heading"><h2>Top-selling SKU · sales value</h2></div><ValueBars items={group('product')}/></section><section className="panel"><div className="panel-heading"><h2>Production vs. sales</h2></div><SampleTrend s={s} kind="variance"/></section></div></>}
function ValueBars({items}:any){const max=Math.max(1,...items.map((r:any)=>r[1]));return <div className="bars">{items.map(([name,value]:any)=><div className="bar-row" key={name}><div><span>{name}</span><strong>₱{fmt(value)}</strong></div><div className="bar-track"><div style={{width:`${value/max*100}%`}}/></div></div>)}</div>}






