export const roles = ['Super Admin','Inventory Manager','Warehouse Manager','Warehouse Staff','Distributor','Production Owner','Finance/Admin'];
export const regions = ['Luzon','Mindanao','Modern Trade','Region A'];
export const prototypeDefaults={
 workflows:[
  {id:'wf-receipt',name:'Standard goods receipt',process:'Goods receipt',steps:'Gate Security → Warehouse Staff → Supervisor',condition:'Supervisor approval required when the count differs or the receipt exceeds 5,000 cases.',status:'Active'},
  {id:'wf-order',name:'Order tolerance approval',process:'Order approval',steps:'Sales Operations → Production Owner',condition:'Required when an order exceeds available inventory but remains within the configured tolerance.',status:'Active'},
  {id:'wf-reconciliation',name:'Weekly distributor reconciliation',process:'Inventory reconciliation',steps:'Inventory Analyst → Distributor Manager → Inventory Manager',condition:'Approval required when variance exceeds 2%.',status:'Active'}
 ],
 alerts:[
  {id:'alert-expiry',name:'Near-expiry inventory',type:'Near expiry',leadTime:30,threshold:'Any batch inside lead time',recipients:'Inventory Manager, Warehouse Manager',status:'Active'},
  {id:'alert-stockout',name:'Stock-out risk',type:'Stock-out',leadTime:0,threshold:'Days of cover below 7',recipients:'Operations, Production Owner',status:'Active'},
  {id:'alert-dead',name:'Dead stock review',type:'Dead stock',leadTime:0,threshold:'No sell-through for 60 days',recipients:'Inventory Manager, Sales Operations',status:'Active'}
 ],
 currencies:[
  {id:'currency-php',code:'PHP',name:'Philippine peso',source:'Bangko Sentral reference',rate:1,rateDate:'2026-09-07',usageRule:'Order received time',status:'Active'},
  {id:'currency-usd',code:'USD',name:'US dollar',source:'Configured market feed',rate:57.25,rateDate:'2026-09-07',usageRule:'Invoice time',status:'Active'}
 ],
 countries:[
  {id:'country-ph-luzon',country:'Philippines',region:'Luzon',timeZone:'Asia/Manila',status:'Active'},
  {id:'country-ph-mindanao',country:'Philippines',region:'Mindanao',timeZone:'Asia/Manila',status:'Active'},
  {id:'country-ph-modern',country:'Philippines',region:'Modern Trade',timeZone:'Asia/Manila',status:'Active'}
 ],
 reasons:[
  {id:'reason-damage',name:'Damaged',category:'Damage / consumption',status:'Active'},
  {id:'reason-miscount',name:'Miscount',category:'Stock adjustment',status:'Active'},
  {id:'reason-consumption',name:'Internal consumption',category:'Damage / consumption',status:'Active'},
  {id:'reason-expiry',name:'Expired',category:'Returns',status:'Active'},
  {id:'reason-other',name:'Other',category:'Reconciliation',status:'Active'}
 ],
 shipments:[]
};
export function initialState(){return {version:1,products:[{id:'mango',name:'Mango',flavor:'Mango',brand:'Bonko',status:'Active',unit:'case',carton:40,reorder:0},{id:'blackcurrant',name:'Blackcurrant',flavor:'Blackcurrant',brand:'Bonko',status:'Active',unit:'case',carton:40,reorder:0}],warehouses:[],batches:[],movements:[],distributors:[],orders:[],invoices:[],suppliers:[],purchases:[],returns:[],counts:[],connections:[],imports:[],reports:[],users:[],barcodes:[],events:[],overrides:[],audit:[],rules:[{id:'acceptance',name:'Order acceptance threshold',multiplier:1.2,status:'Active'}],settings:{receiptApproval:true,expiryDays:30,recipients:['Inventory Manager','Warehouse Manager']},...structuredClone(prototypeDefaults)}}
export function inventory(s,product,warehouse){const batches=s.batches.filter(b=>(!product||b.product===product)&&(!warehouse||b.warehouse===warehouse));const onHand=batches.reduce((n,b)=>n+Number(b.quantity),0);const committed=s.orders.filter(o=>['Allocated','Picked','Packed'].includes(o.status)&&(!product||o.product===product)&&(!warehouse||o.warehouse===warehouse)).reduce((n,o)=>n+Number(o.quantity),0);const expired=batches.filter(b=>b.expiry&&new Date(b.expiry)<new Date(new Date().toISOString().slice(0,10))).reduce((n,b)=>n+b.quantity,0);return {onHand,committed,available:Math.max(0,onHand-committed-expired),expired}}
const allowed={create:['Super Admin','Inventory Manager','Warehouse Manager','Warehouse Staff','Finance/Admin','Production Owner'],approve:['Super Admin','Inventory Manager','Warehouse Manager','Production Owner','Finance/Admin'],export:roles.filter(r=>r!=='Warehouse Staff')};
export function can(role,action){return (allowed[action]||allowed.create).includes(role)}
function check(ok,msg){if(!ok)throw new Error(msg)}
function positive(v,label='Quantity'){const n=Number(v);check(Number.isFinite(n)&&n>0,`${label} must be greater than zero.`);return n}
function find(s,table,id){const r=s[table].find(r=>r.id===id);check(r,`${table} record was not found. Refresh and try again.`);return r}
function capacity(s,warehouse,qty){const w=find(s,'warehouses',warehouse);check(inventory(s,null,warehouse).onHand+qty<=Number(w.capacity),'This receipt exceeds warehouse capacity. Choose another warehouse or update capacity.');}
function issue(s,product,warehouse,quantity,barcode){let q=quantity;const eligible=s.batches.filter(b=>b.product===product&&b.warehouse===warehouse&&b.quantity>0&&(!barcode||b.barcode===barcode)&&(!b.expiry||b.expiry>=new Date().toISOString().slice(0,10))).sort((a,b)=>(a.expiry||'9999').localeCompare(b.expiry||'9999')||(a.manufactured||'').localeCompare(b.manufactured||''));check(eligible.reduce((n,b)=>n+b.quantity,0)>=q,'Insufficient unexpired stock. Receive stock before dispatch.');const parts=[];for(const b of eligible){const take=Math.min(q,b.quantity);if(take){b.quantity-=take;parts.push({...b,quantity:take})}q-=take;if(q===0)break;}return parts}
function invoice(s,order,id){if(!s.invoices.some(i=>i.order===order.id))s.invoices.push({id:id+'-invoice',order:order.id,distributor:order.distributor,status:'Awaiting amount',amount:null,paid:0,currency:find(s,'distributors',order.distributor).currency||'PHP',created:new Date().toISOString()})}
export function apply(s,input){const {action,table,id,role='Inventory Manager'}=input;const data={...input.data};check(roles.includes(role),'Unknown role.');check(can(role,action==='transition'?'approve':'create'),'Your role does not have permission for this action.');const uid=globalThis.crypto.randomUUID();const now=new Date().toISOString();let before=null,result=null;const admin=['users','rules','settings','connections','workflows','alerts','currencies','countries','reasons'];if(admin.includes(table))check(['Super Admin','Inventory Manager'].includes(role),'Only an administrator or inventory manager can change this configuration.');
if(action==='create'){
check(['products','warehouses','distributors','orders','suppliers','purchases','returns','counts','connections','reports','users','barcodes','events','overrides','movements','imports','workflows','alerts','currencies','countries','reasons','shipments'].includes(table),'Unsupported record type.');
if(['products','warehouses','distributors','suppliers','connections','reports','users','workflows','alerts','reasons'].includes(table))check(data.name?.trim(),'Name is required.');
if(table==='products'){check(data.flavor&&data.unit,'Flavor and base unit are required.');check(!s.products.some(p=>data.sku&&p.sku===data.sku),'This SKU already exists.');data.reorder=Number(data.reorder||0);data.carton=positive(data.carton,'Cases per carton');}
if(table==='warehouses'){data.capacity=positive(data.capacity,'Capacity');check(data.region&&data.location&&data.distributor,'Region, location, and distributor name are required.');}
if(table==='distributors'){check(data.region&&data.contact&&data.currency&&data.exchangeTiming,'Region, contact, currency, and exchange-rate timing are required.');data.stock=0;data.sold=0;}
if(['orders','movements','purchases','returns','counts','barcodes'].includes(table))find(s,'products',data.product);
if(['movements','counts','barcodes'].includes(table))find(s,'warehouses',data.warehouse);
if(['orders','purchases','returns','movements'].includes(table)){data.quantity=positive(data.quantity);check(Number.isInteger(data.quantity),'Case quantities must be whole numbers.');}
if(['orders','returns'].includes(table))find(s,'distributors',data.distributor);
if(table==='orders'){check(data.contact&&data.channel&&data.delivery,'Contact, channel, and required delivery date are required.');check(data.delivery>=now.slice(0,10),'Delivery date cannot be in the past.');const p=find(s,'products',data.product);check(p.status!=='Inactive','Inactive products cannot be ordered.');data.loggedBy=role;const available=inventory(s,data.product).available;const threshold=Number(s.rules[0]?.multiplier||1.2);data.status=data.quantity<=available*threshold?'Approved':'Pending';data.approvalReason=data.status==='Pending'?'Above acceptance threshold; production-owner review required.':'Within configured acceptance threshold.';}
if(table==='movements'){check(['Stock In','Stock Out','Stock Transfer','Adjustment'].includes(data.type),'Select a stock action.');check(data.reason,'A reason code is required.');if(data.type==='Stock In'){check(data.batch&&data.manufactured&&data.expiry,'Batch, manufacture date, and expiry are required.');check(data.manufactured<=data.expiry,'Expiry must be after manufacture date.');check(data.expiry>=now.slice(0,10),'Expired stock cannot be received into available inventory.');capacity(s,data.warehouse,data.quantity);data.status=s.settings.receiptApproval?'Awaiting recount':'Received';if(!s.settings.receiptApproval)s.batches.push({id:uid+'-batch',product:data.product,warehouse:data.warehouse,batch:data.batch,manufactured:data.manufactured,expiry:data.expiry,quantity:data.quantity,barcode:data.barcode||''});}else{check(data.quantity<=inventory(s,data.product,data.warehouse).available,'Quantity exceeds available unexpired stock. Allocated stock is protected.');if(data.type==='Stock Transfer'){check(data.destination&&data.destination!==data.warehouse,'Choose a different destination warehouse.');capacity(s,data.destination,data.quantity);}const parts=issue(s,data.product,data.warehouse,data.quantity,data.barcode);if(data.type==='Stock Transfer')for(const p of parts)s.batches.push({...p,id:globalThis.crypto.randomUUID(),warehouse:data.destination});data.status=data.type==='Stock Transfer'?'Received':data.type==='Adjustment'?'Approved':'Dispatched';}}
if(table==='counts'){data.expected=inventory(s,data.product,data.warehouse).onHand;data.actual=Number(data.actual);check(Number.isInteger(data.actual)&&data.actual>=0,'Actual quantity must be a non-negative whole number.');data.variance=data.actual-data.expected;check(data.reason,'A variance/count reason is required.');data.status='Awaiting approval';}
if(table==='purchases'){find(s,'suppliers',data.supplier);check(data.delivery,'Expected receipt date is required.');data.status='Open';}
if(table==='returns'){check(['Before dispatch','After distributor receipt'].includes(data.damageStage),'Select where damage occurred.');check(data.reason,'Return reason is required.');data.liability=data.damageStage==='Before dispatch'?'Company':'Distributor';data.status='Pending review';}
if(table==='barcodes'){const b=find(s,'batches',data.batch);check(b.product===data.product&&b.warehouse===data.warehouse,'The batch must match the selected product and warehouse.');check(data.code&&/^[\x20-\x7E]+$/.test(data.code),'Use printable ASCII characters for a Code 128 barcode.');check(!s.barcodes.some(b=>b.code===data.code),'This barcode is already linked.');b.barcode=data.code;}
if(table==='users'){check(roles.includes(data.role),'Select a valid role.');check(data.email&&data.email.includes('@'),'Enter a valid email.');data.status='Active';}
if(table==='connections')data.status='Not connected';
if(table==='workflows'){check(data.process&&data.steps&&data.condition,'Process, approval steps, and conditions are required.');}
if(table==='alerts'){check(data.type&&data.recipients,'Risk type and recipients are required.');data.leadTime=Number(data.leadTime||0);check(data.leadTime>=0,'Alert lead time cannot be negative.');}
if(table==='currencies'){check(data.code&&data.name&&data.source&&data.usageRule,'Currency code, name, source, and rate rule are required.');data.rate=positive(data.rate,'Sample rate');check(!s.currencies.some(c=>c.code===data.code),'This currency code already exists.');}
if(table==='countries')check(data.country&&data.region&&data.timeZone,'Country, region, and time zone are required.');
if(table==='shipments'){check(data.reference&&data.dispatchDate&&data.deliveryDate&&data.initiatedBy,'Reference, dates, and initiator are required.');find(s,'distributors',data.distributor);find(s,'warehouses',data.warehouse);find(s,'orders',data.order);check(data.dispatchDate<=data.deliveryDate,'Expected delivery cannot be before dispatch.');}
if(table==='reports')data.status='Scheduled locally';
if(table==='overrides')check(data.reason?.trim(),'Explain why you are overriding this recommendation.');
if(table==='imports'){check(Array.isArray(data.rows)&&data.rows.length,'Import has no valid rows.');find(s,'distributors',data.distributor);for(const row of data.rows){const p=s.products.find(p=>p.id===row.product||p.name===row.product||p.sku===row.product);check(p,`Unknown product: ${row.product}`);check(Number.isFinite(Number(row.stock))&&Number(row.stock)>=0&&Number.isFinite(Number(row.sold))&&Number(row.sold)>=0,'Stock and sell-through must be non-negative numbers.');row.product=p.id;}const d=find(s,'distributors',data.distributor);d.positions=data.partial?[...(d.positions||[]).filter(p=>!data.rows.some(r=>r.product===p.product)),...data.rows]:data.rows;d.stock=d.positions.reduce((n,r)=>n+Number(r.stock),0);d.sold=d.positions.reduce((n,r)=>n+Number(r.sold),0);d.lastSync=now;if(data.mapping)d.mapping=data.mapping;data.status='Reconciled';}
result={...data,id:uid,created:now,status:data.status||'Active'};s[table].unshift(result);if(table==='orders'&&result.status==='Approved')invoice(s,result,uid);
}else if(action==='transition'){
const row=find(s,table,id);before=structuredClone(row);const next=data.status;
if(table==='orders'){
const valid={Pending:['Approved','Rejected'],Approved:['Allocated','Cancelled'],Allocated:['Picked'],Picked:['Packed'],Packed:['Fulfilled'],Fulfilled:['Invoiced']};check(valid[row.status]?.includes(next),'This order action is no longer available.');
if(row.status==='Pending'){check(['Production Owner','Super Admin'].includes(role),'This decision must be made by the production owner.');check(data.reason&&data.productionDate,'Production date and approval/rejection reasoning are required.');if(next==='Approved')check(data.productionDate<=row.delivery,'Production completes after required delivery. Reject or revise delivery.');}
if(next==='Approved')invoice(s,row,uid);
if(next==='Allocated'){find(s,'warehouses',data.warehouse);check(row.quantity<=inventory(s,row.product,data.warehouse).available,'Insufficient available stock at this warehouse.');row.warehouse=data.warehouse;}
if(next==='Fulfilled'){issue(s,row.product,row.warehouse,row.quantity);const d=find(s,'distributors',row.distributor);d.stock=Number(d.stock||0)+row.quantity;d.positions=d.positions||[];const position=d.positions.find(p=>p.product===row.product);if(position)position.stock=Number(position.stock||0)+row.quantity;else d.positions.push({product:row.product,stock:row.quantity,sold:0});s.movements.unshift({id:uid+'-dispatch',type:'Stock Out',distributor:row.distributor,order:row.id,product:row.product,warehouse:row.warehouse,quantity:row.quantity,reason:'Order fulfillment',status:'Dispatched',created:now});}
}else if(table==='movements'){check(row.status==='Awaiting recount','Receipt has already been processed.');check(['Warehouse Manager','Super Admin','Inventory Manager'].includes(role),'A warehouse supervisor must approve this receipt.');check(['Received','Rejected'].includes(next),'Invalid receipt action.');if(next==='Received'){check(Number(data.recount)===row.quantity,'Recount does not match the initial count. Reject the receipt and enter a corrected receipt.');capacity(s,row.warehouse,row.quantity);s.batches.push({id:uid+'-batch',product:row.product,warehouse:row.warehouse,batch:row.batch,manufactured:row.manufactured,expiry:row.expiry,quantity:row.quantity,barcode:row.barcode||''});}}
else if(table==='counts'){check(row.status==='Awaiting approval','Count already processed.');check(['Approved','Rejected'].includes(next),'Invalid count action.');if(next==='Approved'){check(inventory(s,row.product,row.warehouse).onHand===row.expected,'Stock changed after this count. Reject and recount to avoid overwriting movements.');if(row.variance<0){check(-row.variance<=inventory(s,row.product,row.warehouse).available,'Variance would consume committed stock. Resolve allocations first.');issue(s,row.product,row.warehouse,-row.variance)}else if(row.variance>0){check(data.batch&&data.expiry&&data.manufactured,'Positive variance needs batch and date details.');check(data.expiry>=now.slice(0,10)&&data.manufactured<=data.expiry,'Enter valid manufacture and expiry dates.');capacity(s,row.warehouse,row.variance);s.batches.push({id:uid,product:row.product,warehouse:row.warehouse,quantity:row.variance,batch:data.batch,expiry:data.expiry,manufactured:data.manufactured});}s.movements.unshift({id:uid+'-count',type:'Adjustment',product:row.product,warehouse:row.warehouse,quantity:row.variance,reason:row.reason,status:'Approved',created:now});}}
else if(table==='returns'){check(row.status==='Pending review','Return already reviewed.');check(['Approved','Rejected'].includes(next),'Invalid decision.');check(data.reason,'Record the policy decision reason.');}
else if(table==='purchases'){check(row.status==='Open'&&next==='Closed','Only open purchase orders can be closed.');check(s.movements.some(m=>m.purchase===id&&m.status==='Received'),'Receive and approve the linked purchase stock before closing.');}
else throw new Error('Unsupported transition.');
Object.assign(row,data,{updated:now});result=row;
}else if(action==='update'){
if(table==='settings'){before={...s.settings};check(Number(data.expiryDays)>=0,'Alert lead time cannot be negative.');Object.assign(s.settings,data);result=s.settings;}
else{check(['products','warehouses','distributors','orders','rules','invoices','users','reports','connections','workflows','alerts','currencies','countries','reasons','shipments'].includes(table),'This record cannot be edited.');const row=find(s,table,id);before={...row};if(table==='orders'){check(['Pending','Approved'].includes(row.status),'Only pending or approved orders can be edited.');find(s,'products',data.product);find(s,'distributors',data.distributor);data.quantity=positive(data.quantity);check(Number.isInteger(data.quantity),'Case quantities must be whole numbers.');check(data.contact&&data.channel&&data.delivery,'Contact, channel, and required delivery date are required.');check(data.delivery>=now.slice(0,10),'Delivery date cannot be in the past.');const p=find(s,'products',data.product);check(p.status!=='Inactive','Inactive products cannot be ordered.');const available=inventory(s,data.product).available;const threshold=Number(s.rules[0]?.multiplier||1.2);data.status=data.quantity<=available*threshold?'Approved':'Pending';data.approvalReason=data.status==='Pending'?'Above acceptance threshold; production-owner review required.':'Within configured acceptance threshold.';}if(table==='invoices'){check(['Super Admin','Finance/Admin'].includes(role),'Finance must update payment records.');data.amount=positive(data.amount,'Invoice amount');data.paid=Number(data.paid||0);check(data.paid>=0&&data.paid<=data.amount,'Payment must be between zero and invoice total.');check(data.due,'Payment due date is required.');data.status=data.paid===data.amount?'Paid':data.paid>0?'Partial':data.due<now.slice(0,10)?'Overdue':'Unpaid';}if(table==='rules')data.multiplier=positive(data.multiplier,'Threshold multiplier');if(table==='products'){check(data.name&&data.flavor&&data.unit,'Product name, flavor, and base unit are required.');data.reorder=Number(data.reorder||0);check(Number.isFinite(data.reorder)&&data.reorder>=0,'Reorder level must be non-negative.');data.carton=positive(data.carton,'Cases per carton');check(!s.products.some(p=>p.id!==id&&data.sku&&p.sku===data.sku),'This SKU already exists.');}if(table==='warehouses'){data.capacity=positive(data.capacity,'Capacity');check(data.distributor,'Distributor name is required.');check(data.capacity>=inventory(s,null,id).onHand,'Capacity cannot be below current stock.');}Object.assign(row,data,{updated:now});result=row;}
}else throw new Error('Unsupported action.');
s.audit.unshift({id:uid,time:now,user:role,action:action==='transition'?data.status:action,table,record:result?.id||table,previous:before?JSON.stringify(before):'—',value:JSON.stringify(result),reason:data.reason||data.notes||'Record saved'});s.version++;return {state:s,result};}





